spring:
  datasource:
    url: jdbc:postgresql:/warehouse_postgres/:5432/warehouseDB
    username: hamza
    password: mypass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/logistics-realm

server:
  port: 8090